name: Create Tag

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    #- name: 'Get Previous tag'
    #  id: previoustag
    #  uses: "WyriHaximus/github-action-get-previous-tag@v1"
    #- name: 'Get next minor version'
    #  id: semvers
    #  uses: "WyriHaximus/github-action-next-semvers@v1"
    #  with:
    #    version: ${{ steps.previoustag.outputs.tag }}
        
    - name: "Write Previus tag:"
      run: echo "${{ steps.previous_step.outputs.tagname }}"
