name: Create Tag

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Klemensas/action-autotag@stable
      id: create_tag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ steps.create_tag.outputs.tagname }}"
        prerelease: false
    - name: "Write Previus tag:"
      run: echo "${{ steps.create_tag.outputs.tagname }}"
