name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # if: contains(github.event.head_commit.message, '--minor')
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Modify artifacts.txt
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: ./.github/workflows/artifact.txt
          body: "overwrite file content"
          overwrite: 'true'
          
      
