# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ github.event.head_commit.message }}
          echo "set 1 >> ${{ vars.BREAKING_NUM }}"
          echo "major version: ${{ vars.BREAKING_NUM }}"
