# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    if: contains(${{ github.event.head_commit.message }}, '--minor')
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo ${{ github.event.head_commit.message }}
          
      - name: Set a persistent value
        id: set_persistent_value
        uses: aaimio/set-persistent-value@v1.2.1
        with:
          key: foo
          value: bar
          access_token: ${{ secrets.PERSISTENT_VALUE_ACCESS_TOKEN }}


      - name: Get a persistent value
        id: get_persistent_value
        uses: aaimio/get-persistent-value@v1.2.1
        with:
          key: foo
          access_token: ${{ secrets.PERSISTENT_VALUE_ACCESS_TOKEN }}
      - name: Some other step
        run: |
          echo ${{ steps.get_persistent_value.outputs.value }}
